export const currentNodeProviderKey = Symbol('currentNode')
export const psychProviderKey = Symbol('psych')
export const hasPsychProviderKey = Symbol('hasPsych')
export const emitterProviderKey = Symbol('emitter')
export const variablesType = Symbol('variables')